module.exports = {
    easy: [
        {category: "cartoon", name: "Rick and Morty", url: "https://i.postimg.cc/xC7BVwvP/rick-and-morty-watch-i50046.jpg"},
        {category: "person", name: "Barack Obama", url: "https://i.postimg.cc/ZKnvMrWx/Official-portrait-of-Barack-Obama-cropped.jpg"},
        {category: "furniture", name: "Chair", url: "https://i.postimg.cc/x8RG3YFj/Chair-1.jpg"},
        {category: "TV Show", name: "Breaking Bad", url: "https://i.postimg.cc/Y0m86JBh/HD-wallpaper-breaking-bad-brba-breaking-bad-season-3-heisenberg-jesse-pinkman-sky-walter-white.jpg"},
        {category: "country", name: "The United States of America", url: "https://i.postimg.cc/g08Y70yD/close-up-shot-of-an-american-flag-3e3eee-1600.jpg"},
        {category: "app", name: "TikTok", url: "https://i.postimg.cc/t4DQfV8p/tiktok-icon2.png"},
        {category: "game", name: "Fortnite", url: "https://i.postimg.cc/wvt4TtMK/1207.webp"},
        {category: "person", name: "Donald Trump", url: "https://i.postimg.cc/xT9rgChY/Donald-Trump-by-Gage-Skidmore.jpg"},
        {category: "animal", name: "Dog", url: "https://i.postimg.cc/6pdLkXHt/image.jpg"},
        {category: "animal", name: "Cat", url: "https://i.postimg.cc/nFfTd7F8/adorable-fluffy-cat.jpg"},
        {category: "brand", name: "Ferrari", url: "https://i.postimg.cc/bJx5JCfk/logo-Ferrari.jpg"},
        {category: "planet", name: "Jupiter", url: "https://i.postimg.cc/cHqCq6LJ/28284959668-650c93fb69-b.jpg"},
        {category: "monument", name: "The Eiffel Tower", url: "https://i.postimg.cc/0jKrhmpr/Eiffel-tower-paris-france.jpg"},
        {category: "object", name: "Map", url: "https://i.postimg.cc/wjwyy6Tq/pexels-photo-1252500.jpg"},
        {category: "app", name: "Twitter", url: "https://i.postimg.cc/Pf1CbbrF/social-media-twitter-logo-blue-isolated-free-vector.jpg"},
        {category: "app", name: "Instagram", url: "https://i.postimg.cc/MHYZCDn6/instagram-icon-1057-2227.webp"},
        {category: "game", name: "Street Fighter", url: "https://i.postimg.cc/13xhGdML/5-1-1-1.jpg"},
        {category: "animal", name: "Monkey", url: "https://i.postimg.cc/d36Rs3n8/monkey-bananav3.jpg"},
        {category: "animal", name: "Gorilla", url: "https://i.postimg.cc/05hZNK8C/15452888118-d1f36db7fb-b.jpg"},
        {category: "country", name: "France", url: "https://i.postimg.cc/QCDzHBDC/285049-2022x1348-french-flag-in-paris.jpg"},
        {category: "character", name: "Darth Vader", url: "https://i.postimg.cc/X7x4wWpX/32461333995-087c9243f1-b.jpg"},
        {category: "object", name: "Nail clippers", url: "https://i.postimg.cc/Sx8dBSCx/Nailclippers3.jpg"},
        {category: "object", name: "Fork", url: "https://i.postimg.cc/85nLF9MY/35244123291-a9a9ba6f0c-b.jpg"},
        {category: "object", name: "Spoon", url: "https://i.postimg.cc/rpx2hR8y/1733617229-a77bfacb6d-c.jpg"},
        {category: "person", name: "Martin Luther King Jr.", url: "https://i.postimg.cc/FKnBm9Dd/Martin-luther-king-2-cropped.jpg"},
        {category: "animal", name: "Rabbit", url: "https://i.postimg.cc/vZBV69WK/87132-2x3.webp"},
        {category: "animal", name: "Guinea Pig", url: "https://i.postimg.cc/6pgy2P67/Basic-Guinea-Pig-Care.jpg"},
        {category: "animal", name: "Elephant", url: "https://i.postimg.cc/xTW2KVHS/6987533681-2112daf5ea-b.jpg"},
        {category: "animal", name: "Zebra", url: "https://i.postimg.cc/qqzP31vR/plains-zebra-thumb-3x4.webp"},
        {category: "animal", name: "Giraffe", url: "https://i.postimg.cc/76QcwSny/pexels-photo-6404790.jpg"},
        {category: "animal", name: "Tiger", url: "https://i.postimg.cc/HWrW52KX/Medium-WW226367.jpg"},
        {category: "animal", name: "Koala", url: "https://i.postimg.cc/0y09xHMR/Some-image-width-800-25af59c.jpg"},
        {category: "animal", name: "Bald Eagle", url: "https://i.postimg.cc/fTxNjgvt/Bald-eagle-Adult.jpg"},
        {category: "animal", name: "Snake", url: "https://i.postimg.cc/7ZYWGBty/How-to-Avoid-Snakes-Slithering-Up-Your-Toilet-shutterstock-780480850-1.jpg"},
        {category: "animal", name: "Dolphin", url: "https://i.postimg.cc/RFrdRGdh/Dolphin-fasting.jpg"},
        {category: "animal", name: "Kangaroo", url: "https://i.postimg.cc/5NtB8ZJp/1928593646-7d234c9f28-b.jpg"},
        {category: "animal", name: "Bear", url: "https://i.postimg.cc/Bnr29bKw/2010-brown-bear.jpg"},
        {category: "movie", name: "Star Wars", url: "https://i.postimg.cc/zXmjYdYk/hero-the-history-of-star-wars-movies.jpg"},
        {category: "animal", name: "Owl", url: "https://i.postimg.cc/hvLGH4VT/1200px-Bubo-virginianus-06.jpg"},
        {category: "animal", name: "Horse", url: "https://i.postimg.cc/9zHWp6S0/photo-1598974357801-cbca100e65d3-ixlib-rb-1-2.jpg"},
        {category: "animal", name: "Donkey", url: "https://i.postimg.cc/Sxps79Fd/World-Donkey-Day-jpg.webp"},
        {category: "animal", name: "Duck", url: "https://i.postimg.cc/cHz27fjL/Male-mallard-duck-2.jpg"},
        {category: "animal", name: "Goat", url: "https://i.postimg.cc/5Nzd3kfd/Hausziege-04.jpg"},
        {category: "planet", name: "Mars", url: "https://i.postimg.cc/zBpW4j5q/mars.jpg"},
        {category: "planet", name: "Saturn", url: "https://i.postimg.cc/FNfLcbdq/Fad-Qq-Lx-XEAEZNxs.jpg"},
        {category: "anime", name: "Naruto Shippuden", url: "https://i.postimg.cc/qMfpCsgL/naruto-shippuden-anime.jpg", alias: ["Naruto"]},//Naruto can work less points ill add this sign (-)//
        {category: "anime", name: "Death Note", url: "https://i.postimg.cc/7YPhwQrN/image.jpg"},
        {category: "anime", name: "My Hero Academia", url: "https://i.postimg.cc/pX9NfDfH/5121872-043974e0-8c3c-42fb-95f1-11b11c3a3a30.jpg", alias: ["Naruto"]},
        {category: "anime", name: "One Punch Man", url: "https://i.postimg.cc/FFd2VKvC/affiche-370x0.jpg"},
        {category: "anime", name: "Your Name", url: "https://i.postimg.cc/brgQdDvV/image.jpg"},
        {category: "anime", name: "Howl's Moving Castle", url: "https://i.postimg.cc/RF6SNjVk/il-570x-N-2710747754-8ayc.webp"},
        {category: "cartoon", name:"The Simpsons", url: "https://i.postimg.cc/kGGx6Mtn/fox-the-simpsons-1420x798.jpg"},
        {category: "cartoon", name: "Paw Patrol", url: "https://i.postimg.cc/jSc372Df/1200x675mf.jpg"},
        {category: "cartoon", name: "Tom and Jerry", url: "https://i.postimg.cc/wv4dcF3h/37c2eee04ebc3b45d27003352e82acf0-wallpaper-for-phone-cartoon-wallpaper.jpg"},
        {category: "person", name: "Joaquin Phoenix", url: "https://i.postimg.cc/DZ48GWwy/LTIy-NDMuan-Bl-Zw.jpg"},
        {category: "person", name: "Taylor Swift", url: "https://i.postimg.cc/fynmR4hL/taylor-swift-3664.jpg"},
        {category: "person", name: "Rihanna", url: "https://i.postimg.cc/52SZb1LP/Rihanna.jpg"},
        {category: "person", name: "Beyonce", url: "https://i.postimg.cc/rm4PKL7R/beyonce-press-2022-cr-parkwood-entertaiment-billboard-1548.jpg"},
        {category: "person", name: "Drake", url: "https://i.postimg.cc/sgqP1HSt/rs-1200x1200-201012052848-1200-Drake-Euphoria-Aubrey-Drake-Graham-ch-101220.jpg"},
        {category: "person", name: "The Weekend", url: "https://i.postimg.cc/tJFPZ93f/rs-1200x1200-210207174748-1200-the-weeknd-super-bowl-2021-ct.webp"},
        {category: "person", name: "Ariana Grande", url: "https://i.postimg.cc/g2ZNWLBy/24-JPGRANDE1-super-Jumbo.jpg"},
        {category: "person", name: "Elon Musk", url: "https://i.postimg.cc/s2pzvX17/1200px-Elon-Musk-Royal-Society-crop2.jpg"},
        {category: "person", name: "Selena Gomez", url: "https://i.postimg.cc/ZRsjF8MN/newFile.jpg"},
        {category: "person", name: "Justin Bieber", url: "https://i.postimg.cc/NMbJ5qtQ/singer-songwriter-justin-bieber-attends-the-2014-young-news-photo-452816022-1543262087.jpg"},
        {category: "person", name: "Cristiano Ronaldo", url: "https://i.postimg.cc/v8XPPRcW/cd559663f19a01c3f2588133067a06ef.jpg"},
        {category: "person", name: "Dwayne Johnson", url: "https://i.postimg.cc/KYrw7Jwj/00-tout-the-rock.jpg"},
        {category: "person", name: "Tom Hanks", url: "https://i.postimg.cc/RhBc1x6J/Tom-hanks.jpg"},
        {category: "person", name: "Eminem", url: "https://i.postimg.cc/JnfGZNFT/eminem-photo-by-dave-j-hogan-getty-images-entertainment-getty-187596325.jpg"},
        {category: "TV Show", name: "The Big Bang Theory", url: "https://i.postimg.cc/yddbc9RS/142694.jpg"},
        {category: "TV Show", name: "Euphoria", url: "https://i.postimg.cc/jj7ynSg4/zendaya-en-euphoria-6862.jpg"},
        {category: "TV Show", name: "The Office", url: "https://i.postimg.cc/1z5HjqHR/office-leaving-netflix.png"},
        {category: "TV Show", name: "Malcolm in the Middle", url: "https://i.postimg.cc/0y9F9rfF/image.jpg", alias: ["Malcolm"]}, //Malcolm (-)//
        {category: "TV Show", name: "Stranger Things", url: "https://i.postimg.cc/D0FVJXwN/Phillips-Stranger-Things-Kids-S3.jpg"},
        {category: "TV Show", name: "Lucifer", url: "https://i.postimg.cc/mkzVS1sX/MV5-BOWFj-Mm-E5-Mzgt-ZTFh-OS00-M2-Uz-LWEy-MGUt-Zj-Ix-ZDFi-Zj-I5-Nj-Qw-Xk-Ey-Xk-Fqc-Gde-QXVy-MTYz-MDM0-NTU-V1.jpg"},
        {category: "TV Show", name: "Squid game", url: "https://i.postimg.cc/W4cH5nWB/5ZHq1PK.png"},
        {category: "animal", name: "Cheetah", url: "https://i.postimg.cc/Kcr6KdYd/23517432926-735329bbcc-b.jpg"},
        {category: "app", name: "WhatsApp", url: "https://i.postimg.cc/Gh6Z8YD5/original.jpg"},
        {category: "app", name: "Steam", url: "https://i.postimg.cc/tJcWC9YL/steam-logo-blurred-background.jpg"},
        {category: "app", name: "Twitch", url: "https://i.postimg.cc/XvZJ49w7/21k-Rx-CJs-UL.png"},
        {category: "brand", name: "Amazon", url: "https://i.postimg.cc/FHk5Kpnq/amazon-600.png"},
        {category: "brand", name: "eBay", url: "https://i.postimg.cc/02s1N7q2/VCT3-V3-ACA5-DI7-A2-QNCC2-GSNOW4.jpg"},
        {category: "brand", name: "BMW", url: "https://i.postimg.cc/mDk28CrG/23bmw1-mobile-Master-At3x.jpg"},
        {category: "brand", name: "Adidas", url: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg"},
        {category: "brand", name: "Nike", url: "https://i.postimg.cc/CLcNBVfr/nike-voguebus-Edward-Berthelot-Getty-Images-feb-21-story.jpg"},
        {category: "brand", name: "Starbucks", url: "https://i.postimg.cc/G2sLYr2F/1481130851-7484.webp"},
        {category: "country", name: "Japan", url: "https://i.postimg.cc/d3pG6JmJ/colton-jones-p8-URGduy-Eg-unsplash-scaled.jpg"},
        {category: "country", name: "Egypt", url: "https://i.postimg.cc/FK6Cfk7K/cairo-egypt-03.jpg"},
        {category: "country", name: "Canada", url: "https://i.postimg.cc/gJQ0BsrP/Canada-Flag-Lake-Louise-1024x683.jpg"},
        {category: "country", name: "China", url: "https://i.postimg.cc/Y2RngP4V/photo-1589889353869-b0c95b307770-ixlib-rb-1-2.jpg"},
        {category: "country", name: "India", url: "https://i.postimg.cc/zDpNB0qD/Indian-National-Flag-What-every-Indian-citizen-must-know.webp"},
        {category: "game", name: "Minecraft", url: "https://i.postimg.cc/gjKtMSkM/c82a607ee93697da806c5263dac3741e-minecraft-account-minecraft-stuff.jpg"},
        {category: "game", name: "Grand Theft Auto", url: "https://i.postimg.cc/vbRvrPwH/grand-theft-auto-v-protagonists-1644067724.jpg"},
        {category: "game", name: "Call of Duty", url: "https://i.postimg.cc/k7N9JhqV/MWII-tall-tile.jpg"},
        {category: "objet", name: "Laptop", url: "https://i.postimg.cc/05hW8mLW/149624-laptops-review-hands-on-microsoft-surface-laptop-3-13-5-inch-review-image1-ndijeqz6fw.jpg"}, 
        {category: "objet", name: "Towel", url: "https://i.postimg.cc/KcT7DWHf/sojao-organic-cotton-white-bath-towels-on-green-wall-2400-800x800-crop-center.jpg"},
        {category: "game", name: "Valorant", url: "https://i.postimg.cc/Jh6GppYc/3911016.png"},
        {category: "game", name: "Pac-man", url: "https://i.postimg.cc/brXY5Wxb/pacman.jpg"},
        {category: "game", name: "League of Legends", url: "https://i.postimg.cc/1XnSyHHS/123.png"}, //lol(--)
        {category: "game", name: "Euro Truck Simulator", url: "https://i.postimg.cc/gmPTzcJD/75467-IGDB-272x380.jpg"},
        {category: "movie", name: "The Godfather", url: "https://i.postimg.cc/RV5Bf2L5/im-504443-width-1280-size-1.jpg"},
        {category: "movie", name: "Rocky", url: "https://i.postimg.cc/kMst1rf8/3182354-4232773939-nintc.jpg"},
        {category: "movie", name: "Fast and Furious", url: "https://i.postimg.cc/CKyxmJ89/1897949.jpg"},
        {category: "movie", name: "Terminator", url: "https://i.postimg.cc/c49pxH4m/9a0ea537a08e2fb2c23f84a96af5f04a.jpg"},
        {category: "movie", name: "The Matrix", url: "https://i.postimg.cc/tgYPKBvk/8dbf298e769b82476c82d2268e081b11.jpg"},
        {category: "movie", name: "Harry Potter", url: "https://i.postimg.cc/MGS24LG2/Harry-Potter-8k-Wallpaper.jpg"},
        {category: "movie", name: "Forrest Gump", url: "https://i.postimg.cc/pT7t0Lhk/ebfddd10d2616d6b5226598293f4a65c.jpg"},
        {category: "objet", name: "Pencil case", url: "https://i.postimg.cc/vGyTtnmV/il-570x-N-1848737267-jndn.webp"},
        {category: "objet", name: "Pillow", url: "https://i.postimg.cc/cZqS3SCK/westin-hotel-feather-down-pillow-HB-108-lrg.jpg"},
        {category: "objet", name: "High heels", url: "https://i.postimg.cc/gGj55SrF/9574da5571a63184ea93cb344d0fe71f.jpg"},
        {category: "object", name: "The Moon", url: "https://i.postimg.cc/XnNGHjZv/supermoon-over-washington-dc.jpg"},
        {category: "object", name: "The Sun", url: "https://i.postimg.cc/tRYZq2jV/crop-17387399.jpg"},
        {category: "object", name: "Calculator", url: "https://i.postimg.cc/TTJc5hMd/cd22fa02-3096-4c08-a9b4-4e2d81463997-bc2b44a4fa18d4702df8e5b64b47f62e.jpg"},
        {category: "person", name: "Jesus Christ", url: "https://i.postimg.cc/8pnFBZFk/Jesus-Christ.jpg", alias: ["Jesus"]},
        {category: "person", name: "Bill Gates", url: "https://i.postimg.cc/tprqMBpF/Meeting-with-Bill-Gates-Nov-8-2019-49054512147-cropped.jpg", alias: []},
        {category: "person", name: "Michelle Obama", url: "https://i.postimg.cc/wx82H5zV/St-Felix-Michelle-Obama.jpg", alias: []},
        {category: "person", name: "Scarlett Johansson", url: "https://i.postimg.cc/dJrycM1z/ems.jpg", alias: []},
        {category: "person", name: "Kylie Jenner", url: "https://i.postimg.cc/js90H16S/Kylie-Jenner-in-2021.jpg", alias: []},
        {category: "person", name: "Johnny Depp", url: "https://i.postimg.cc/44f5mfK7/107-Johnny-Depp-jpg.webp", alias: []},
        {category: "person", name: "Elvis Presley", url: "https://i.postimg.cc/Kmm4g1Q8/elvis-presley.jpg", alias: []},
        {category: "person", name: "Michael Jackson", url: "https://i.postimg.cc/5Jr3qVhV/a958c51fbf7447b8876cca7a2e995352-md.jpg", alias: []},
        {category: "person", name: "Diana Spencer", url: "https://i.postimg.cc/5fjymhch/hbz-princess-diana-style-1983-52099299-1500486352.jpg", alias: ["Princess Diana", "Lady Diana"]},
        {category: "person", name: "Jennifer Aniston", url: "https://i.postimg.cc/SQyNY57t/actress-jennifer-aniston-star-as-rachel-green-of-nbcs-news-photo-908311-1565257489.jpg", alias: []},
        {category: "person", name: "Jim Carrey", url: "https://i.postimg.cc/5x6PbNhs/jim-carrey-214542-normal.jpg", alias: []},
        {category: "person", name: "Michael Jordan", url: "https://i.postimg.cc/V1y7PwDF/140507-jordan-0419.jpg", alias: []},
        {category: "person", name: "Jackie Chan", url: "https://i.postimg.cc/B4mcbfck/nra-Zo-Tzw-JQPHsp-AVs-Kfgl3-RXKKa.jpg", alias: []},
        {category: "person", name: "Hillary Clinton", url: "https://i.postimg.cc/Pt0kk7R8/clinton.jpg", alias: []},
        //{category: "person", name: "Cleopatra", url: "", alias: []},
        {category: "person", name: "Nelson Mandela", url: "https://i.postimg.cc/sjPH00dz/A-Corbis-TL007642-brkxd1.jpg", alias: []},
        {category: "person", name: "Lady Gaga", url: "https://i.postimg.cc/fZJ86K4Y/lady-gaga-tattoos.jpg", alias: []},
        {category: "person", name: "Osama Bin Laden", url: "https://i.postimg.cc/KbsNrMKj/Osama-bin-Laden.jpg"},
        {category: "person", name: "Steve Jobs", url: "https://i.postimg.cc/7D2g3Q8t/800px-Steve-Jobs-Headshot-2010-CROP-cropped-2.jpg", alias: []},
        {category: "person", name: "Muhammad Ali", url: "https://i.postimg.cc/09wRPsLd/muhammad-ali-1-raw.jpg", alias: []},
        {category: "person", name: "Lionel Messi", url: "https://i.postimg.cc/PtWgvMfC/lionel-messi-photo-josep-lago-afp-getty-images-664928892-resizedjpg.jpg", alias: []},
        {category: "person", name: "Mark Zuckerberg", url: "https://i.postimg.cc/RvKSGKVB/Mark-Zuckerberg.jpg", alias: []},
        {category: "person", name: "Adele", url: "https://i.postimg.cc/CMgXhnpj/Adele-21-Front-Cover-No-Text.png", alias: []},
        {category: "person", name: "Kate Winstlet", url: "https://i.postimg.cc/J13bwsKw/Kate-Winslet-2009.jpg", alias: []},
        {category: "person", name: "Kanye West", url: "https://i.postimg.cc/x9MsCTg5/kanye-west-attends-the-christian-dior-show-as-part-of-the-paris-fashion-week-womenswear-fall-winter.jpg", alias: []},
        {category: "movie", name: "Up", url: "https://i.postimg.cc/cxdhJpLb/MV5-BMj-Ix-OTI4-Nzky-OV5-BMl5-Ban-Bn-Xk-Ft-ZTcw-Nz-Q5-OTIz-Mw-V1.jpg", alias: []},
        {category: "movie", name: "The Lord of the Rings", url: "https://i.postimg.cc/Dvm69tyk/b88563535z1-20170201115151-000gm3g8f1h2-0-9q4gyzps0x1vb1x2on2-t1880-1592935079.jpg", alias: []},
        {category: "movie", name: "Beauty and the Beast ", url: "https://i.postimg.cc/1PnMJhjD/b7902dabddffa9551cf191d151869dd899-14-beauty-and-the-beast-rsquare-w700.jpg", alias: []},
        {category: "movie", name: "Wall-E", url: "https://i.postimg.cc/VzLCZXk2/bba649471c14e25e2cc1ab18ab9f3406.jpg", alias: []},
        {category: "movie", name: "Avatar", url: "https://i.postimg.cc/PXZyf1Z2/avatar241651147935.webp", alias: []},
        {category: "movie", name: "The Lion King", url: "https://i.postimg.cc/rq35dKqb/experiencing-the-lion-king-for-the-first-time-on-its-25th-an-s1xy.jpg", alias: []},
        {category: "movie", name: "Titanic", url: "https://i.postimg.cc/3KLjKndX/titanic.jpg", alias: []},
        {category: "movie", name: "Toy Story", url: "https://i.postimg.cc/L2RJbjs2/Toy-Story-4-3500-1200x694.jpg", alias: []},
    ],
    medium: [
        {category: "anime", name: "Spirited Away", url: "https://i.postimg.cc/ydTnvFDz/25007888619-1bc2f8c199-b.jpg"},
        {category: "person", name: "Doja Cat", url: "https://i.postimg.cc/Kz0x40mX/Doja-Cat-Elvis.jpg"},
        {category: "furniture", name: "Coffee table", url: "https://i.postimg.cc/X75QpGW3/ss19-h-frmcof.png"},
        {category: "country", name: "Sweden", url: "https://i.postimg.cc/Jzcx5ft2/1200px-Flag-of-Sweden-svg.png"},
        {category: "brand", name: "PlayStation", url: "https://i.postimg.cc/wBqVfwmT/La-derniere-mise-a-jour-de-Sony-garantit-que-les-1200x1200.jpg"},
        {category: "game", name: "Rocket League", url: "https://i.postimg.cc/LsxVrjtk/rl-home-f2p-launch-cross-square-10016.jpg"},
        {category: "cartoon", name: "My Little Pony", url: "https://i.postimg.cc/hGZwRXTm/290941.jpg"},
        {category: "object", name: "Black Hole", url: "https://i.postimg.cc/g04psJL5/49935923702-e808c60963-b.jpg"},
        {category: "object", name: "Water slide", url: "https://i.postimg.cc/CLMQCNsF/10521599566-c7921aa65f-b.jpg"},
        {category: "object", name: "Rubiks Cube", url: "https://i.postimg.cc/6qfNmpyF/Rubiks-Cube-11913436786.jpg"},
        {category: "game", name: "The Witcher 3", url: "https://i.postimg.cc/bv48G57V/Games-The-Witcher-3-Wild-Hunt-They-messed-with-the-wrong-person-RGB.jpg"},
        {category: "person", name: "Emmanuel Macron", url: "https://i.postimg.cc/gjJGnBmn/104510929-emmanuel-macron.jpg"},
        {category: "game", name: "Starcraft 2", url: "https://i.postimg.cc/V5yynx5N/IcltHtX.png"},
        {category: "person", name: "John F. Kennedy", url: "https://i.postimg.cc/85b5001C/John-F-Kennedy.jpg"},
        {category: "event", name: "Rodeo", url: "https://i.postimg.cc/0N86YSRm/rodeo-action-at-the-cheyenne-frontier-days-celebration-in-wyomings-capital-c6127b-1024.jpg"},
        {category: "programming language", name: "Javascript", url: "https://i.postimg.cc/k4hrGQsc/javascript.png"},
        {category: "programming language", name: "Java", url: "https://i.postimg.cc/qq89LP0m/Java-Emblem.jpg"},
        {category: "operating system", name: "Linux", url: "https://i.postimg.cc/TPMn8BXj/linux-tux-hero-2.jpg"},
        {category: "animal", name: "sea turtle", url: "https://i0.wp.com/eos.org/wp-content/uploads/2021/04/loggerhead.jpg?fit=820%2C615"},
        {category: "person", name: "Freddie Mercury", url: "https://i.postimg.cc/CL4G8S9R/Freddie-Mercury-Live-Aid-Queen-Wembley-Stadium-July-13-1985.jpg"},
        {category: "animal", name: "Red Panda", url: "https://i.postimg.cc/QtWCJJt6/Red-Panda-Gizmo-004-Birmingham-Zoo-4-3-21-scaled.jpg"},
        {category: "animal", name: "Chimpanzee", url: "https://i.postimg.cc/T1gyfJvy/new-website-story-banners-7.jpg"},
        {category: "planet", name: "Venus", url: "https://i.postimg.cc/G3JSmw3p/image.jpg"},
        {category: "planet", name: "Uranus", url: "https://i.postimg.cc/dthdSrfK/0x0.jpg"},
        {category: "planet", name: "Neptune", url: "https://i.postimg.cc/BnW8YyDx/neptune-stars-ian-mckinnell.jpg"},
        {category: "planet", name: "Mercury", url: "https://i.postimg.cc/hPswpFNY/01-mercury-pia15190-orig.webp"},
        {category: "person", name: "Edward Snowden", url: "https://i.postimg.cc/N06JZ1ZM/MV5-BZj-Ew-Zm-Iy-Zj-Qt-ZDc2-MS00-Mzdi-LTk5-OTYt-MWE5-Nz-Vj-Nj-E4-MWFm-Xk-Ey-Xk-Fqc-Gde-QXVy-NDkz-NTM2-ODg-V1.jpg"},
        {category: "person", name: "Mr. Beast", url: "https://i.postimg.cc/7PjB4G72/MrBeast.png"},
        {category: "anime", name: "Jojo's Bizarre Adventure", url: "https://i.postimg.cc/QtWXZ7rv/HD-wallpaper-crazy-noizy-bizzare-anime-crazydiamond-jojo-jojo-bizarre-adventures-jojos-bizarre-adven.jpg"}, //jojo (-)
        {category: "anime", name: "Boruto", url: "https://i.postimg.cc/9Q8V4bmv/HD-wallpaper-boruto-uzumaki-sky-blue-sky-moon-sunrise-sunset-boruto-the-next-generations-birds-anime.jpg"},
        {category: "anime", name: "One Piece", url: "https://i.postimg.cc/PqvGCkFw/222382.jpg"},
        {category: "anime", name: "Grave of the Fireflies", url: "https://i.postimg.cc/7PMFG9Xm/4388d968d1e74147a277f339cba533dd.jpg"},
        {category: "anime", name: "My Neighbor Totoro", url: "https://i.postimg.cc/6pHMjVdL/unnamed-32.jpg"},
        {category: "anime", name: "Kiki's Delivery Service", url: "https://i.postimg.cc/G2jX27rD/XROpDY.jpg"}, //kiki (-)
        {category: "cartoon", name: "American Dad", url: "https://i.postimg.cc/kMpxc3j4/1685617615-The-Smith-Family-american-dad-21921979-1280-800.jpg"},
        {category: "cartoon", name: "Oggy and the Cockroaches", url: "https://i.postimg.cc/nMfrPkjd/19-196082-oggy-and-the-cockroaches.jpg"}, //oggy (--)//
        {category: "cartoon", name: "Ben 10", url: "https://i.postimg.cc/7Yr3CvmT/ben-10-aliens-ben-10-alien-force-aliens-25053345-1729-2362.jpg"},
        {category: "cartoon", name: "Totally Spies", url: "https://i.postimg.cc/KY7S2hqr/d8fbecad8c03b43cd6b2564addcb5e6d.jpg"},
        {category: "person", name: "Priyanka Chopra", url: "https://i.postimg.cc/7LkdXQHC/image.jpg"},
        {category: "person", name: "Demi Lovato", url: "https://i.postimg.cc/6pvTCTqW/21-DEMI-LOVATO-promo-new-medium-Square-At3-X-v2.jpg"},
        {category: "person", name: "Chris Brown", url: "https://i.postimg.cc/cChfyCwy/ea1c243d529bcd5df9d5b87868c9cb3861-01-chris-brown-rvertical-w330.jpg"},
        {category: "person", name: "J. Cole", url: "https://i.postimg.cc/qqqvqvWd/J-Cole2.jpg"},
        {category: "person", name: "Childish Gambino", url: "https://i.postimg.cc/kn4Hc8vX/image.jpg", alias: ["Donald Glover"]}, //Donald Glover (=)//
        {category: "person", name: "Kendall Jenner", url: "https://i.postimg.cc/7wt0z2hN/kendall-jenner.jpg"},
        {category: "person", name: "Celine Dion", url: "https://i.postimg.cc/fMgG1BL0/celine-dion-cancer-alzheimer-proche-star-dit-plus-sur-son-etat-sante-1-273x410.jpg"},
        {category: "person", name: "Tiger Woods", url: "https://i.postimg.cc/9VKqFjnx/106854722-1615913058389-gettyimages-1292253394-a53i3760-2020122094036509.jpg"},
        {category: "TV Show", name: "The Fresh Prince of Bel-Air", url: "https://i.postimg.cc/HWZzjvFw/2d4ddca6-087a-4ff4-9097-678761823bab-1-ad173dd0a21c1f84f7aecbec0989fba7.jpg", alias: ["Prince of Bel-Air"]}, //Prince of Bel-Air (-)//
        {category: "TV Show", name: "Supernatural", url: "https://i.postimg.cc/Hdcv9JNd/1544351.jpg"},
        {category: "TV Show", name: "Peaky Blinders", url: "https://i.postimg.cc/4N7X0dcr/39b8038fe9d475b1cf9396146f2f3ce6.jpg"},
        {category: "TV Show", name: "The Witcher", url: "https://i.postimg.cc/vM6hLyCn/henry-cavill-the-witcher-season-2-1639401516.jpg"},
        {category: "TV Show", name: "The Queen's Gambit", url: "https://thebishopstower.com/wp-content/uploads/2021/02/queens-gambit.jpg"},
        {category: "TV Show", name: "Dark", url: "https://i.postimg.cc/FhJhh76R/dark-jonas.jpg"},
        {category: "TV Show", name: "Blacklist", url: "https://i.postimg.cc/np2NCqmh/The-Blacklist-682-682-341-int-c1-c-c-1.jpg"},
        {category: "TV Show", name: "13 Reasons Why", url: "https://i.postimg.cc/Y7TZwdH1/1268964.jpg"},
        {category: "animal", name: "Seahorse", url: "https://i.postimg.cc/LRdCWhtD/Seahorse-female.jpg"},
        {category: "animal", name: "Panther", url: "https://i.postimg.cc/MW55zJrP/10403-2.jpg"},
        {category: "app", name: "Zoom", url: "https://i.postimg.cc/3Y7xMMm0/ZOOM-Login-Page.jpg"},
        {category: "app", name: "Telegram", url: "https://i.postimg.cc/MzhVGfKr/image.jpg"},
        {category: "app", name: "Capcut", url: "https://i.postimg.cc/sjJhKnPt/0b85274abebcf3898ed229539a0edf13.jpg"},
        {category: "app", name: "Epic Games", url: "https://i.postimg.cc/HT3MJztx/840-560.jpg"},
        {category: "brand", name: "AliExpress", url: "https://i.postimg.cc/mbgkBb76/ajudaencontrar-codigo-aliexpress.png"},
        {category: "brand", name: "Shein", url: "https://i.postimg.cc/jxGSHPmG/107089064-1657829516623-gettyimages-1400695652-europapress-4496010-two-people-hold-two-shein-bags-en.jpg"},
        {category: "brand", name: "UPS", url: "https://i.postimg.cc/6wnWs7Dp/About-Card380x280-Atl-Fuel.jpg"},
        {category: "brand", name: "Levi's", url: "https://i.postimg.cc/8Thnd6Xx/105807164-1553192308689gettyimages-1131844055.jpg"},
        {category: "country", name: "Ireland", url: "https://i.postimg.cc/y1XVwxNG/Irish-flag-waving-in-the-wind-in-the-early-morning.jpg"},
        {category: "Country", name: "Algeria", url: "https://i.postimg.cc/WNRG5WDn/16-Algeria.jpg"},
        {category: "Country", name: "Iraq", url: "https://i.postimg.cc/GrvCgHfJ/289eda58df757c634094b59760fc7055.jpg"},
        {category: "country", name: "South Korea", url: "https://i.postimg.cc/pWWPDxWM/south-korea-flag-std.jpg"},
        {category: "Country", name: "Switzerland", url: "https://i.postimg.cc/BsfV7NHt/photo-1618493075021-1bbe5deebedf-ixlib-rb-1-2.jpg"},
        {category: "game", name: "Tetris", url: "https://i.postimg.cc/QX9jmS50/640px-Typical-Tetris-Game-svg.png"},
        {category: "game", name: "Red Dead Redemption", url: "https://i.postimg.cc/fZM6TBLp/w6-Me-Y2-GVk-Nphp-Yj-FX9-V3-TX.jpg"},
        {category: "game", name: "Overwatch", url: "https://i.postimg.cc/DF9ngRPD/maxresdefault.jpg"},
        {category: "game", name: "Animal Crossing", url: "https://i.postimg.cc/XVM5tjcS/animal-crossing-new-horizons-january-artwork-ultra-resolution-banner-790x420.jpg"},
        {category: "game", name: "The Sims", url: "https://i.postimg.cc/vbhMp3rQ/the-sims-4-keyart-jpg-adapt-crop1x1-767p.jpg"},
        {category: "game", name: "Roblox", url: "https://i.postimg.cc/mRr0PBCG/LC-Scene-02-1024x576.png"},
        {category: "game", name: "PUBG", url: "https://i.postimg.cc/Mzz0GKf7/bee290e0-6885-40cd-9a6e-fbb9751ed66e.jpg"},
        {category: "game", name: "The Last of Us", url: "https://i.postimg.cc/xfLqHMWc/lastof-8565.jpg"},
        {category: "movie", name: "The Dark Knight", url: "https://i.postimg.cc/9XV0Bzh1/the-dark-knight-batman-joker.jpg"},
        {category: "movie", name: "Pulp Fiction", url: "https://i.postimg.cc/5bDdcTHW/yojemv6t1nfucjtdopii.jpg"},
        {category: "movie", name: "The Truman Show", url: "https://i.postimg.cc/ZZMKRf9V/image.webp"},
        {category: "movie", name: "Ghostbusters", url: "https://i.postimg.cc/JRQfyn6M/ghostbusters-04.jpg"},
        {category: "movie", name: "El Camino", url: "https://i.postimg.cc/4GjSxVfp/El-Camino-Jesse-Netflix.jpg"},
        {category: "movie", name: "Train to Busan", url: "https://i.postimg.cc/VzTjW9HR/tain-to-busan.jpg"},
        {category: "movie", name: "Jurassic Park", url: "https://i.postimg.cc/LRRjD8vr/jurassic-park-watching-article-Large-v2.jpg"},
        {category: "movie", name: "Django Unchained", url: "https://i.postimg.cc/ZTHvDrw2/image.jpg"},
        {category: "object", name: "Coat", url: "https://i.postimg.cc/hK9CyPN6/27062883-08-B.jpg"},
        {category: "object", name: "Screwdriver", url: "https://i.postimg.cc/wqttQ1sK/STHT60783-1.jpg"},
        {category: "object", name: "Microphone", url: "https://i.postimg.cc/LmrG87Bz/image.jpg"},
        {category: "person", name: "Stephen Curry", url: "https://i.postimg.cc/cW5kxPx6/stephen-curry-gettyimages-538912798-1600jpg.jpg"},
        {category: "object", name: "Whisk", url: "https://i.postimg.cc/SqdckHh5/ikea-365-hjaelte-whisk-stainless-steel-black-0713034-pe729213-s5.webp"},
        {category: "Mythical Beast", name: "Dragon", url: "https://i.postimg.cc/9VD1gWTb/Dragon-Red.jpg"},
        {category: "object", name: "Scale", url: "https://i.postimg.cc/MqbBd4st/Screen-Shot-2022-05-25-at-8-20-05-PM.png"},
        {category: "object", name: "Ruler", url: "https://i.postimg.cc/vYc7Kz1T/3395c7c6c724318f1fd0c315fde22ce0d894bf6846cfe7ab149a5f5562c7ec1b.jpg"},
        {category: "person", name: "Amy Winehouse", url: "https://i.postimg.cc/xntfZnLs/gettyimages-91151868-sq.jpg", alias: []},
        {category: "person", name: "Edith Piaf", url: "https://i.postimg.cc/dv0wTgbr/edith-piaf-72dpi.jpg", alias: []},
        {category: "person", name: "Bob Marley", url: "https://i.postimg.cc/yVn218Y5/gettyimages-84912887-ok-bob-marley-getty-0.jpg", alias: []},
        {category: "person", name: "Anne Frank", url: "https://i.postimg.cc/KbqCCjW3/Anne-Frank.jpg", alias: []},
        {category: "person", name: "George Washington", url: "https://i.postimg.cc/6w4bS0RF/1200px-Gilbert-Stuart-Williamstown-Portrait-of-George-Washington.jpg", alias: []},
        {category: "person", name: "Abraham Lincoln", url: "https://i.postimg.cc/XnLsFDSB/Abraham-Lincoln-O-77-matte-collodion-print.jpg", alias: []},
        {category: "person", name: "J.K. Rowling", url: "https://i.postimg.cc/nn31MjBv/0-J-K-Rowling-Reads-From-New-Harry-Potter-Book.jpg", alias: []},
        {category: "person", name: "Pablo Picasso", url: "https://i.postimg.cc/mLH3dmqw/Getty-Images-2674133.jpg", alias: []},
        {category: "person", name: "John Lennon", url: "https://i.postimg.cc/Vfqrrpp3/biography-5716e51fa67e8.jpg", alias: []},
        {category: "person", name: "Robert Downey Jr.", url: "https://i.postimg.cc/3YJ4NLBc/Robert-Downey.jpg", alias: []},
        {category: "person", name: "Ben Affleck", url: "https://i.postimg.cc/Fmh1CP2H/7-2.jpg", alias: []},
        {category: "person", name: "Angela Merkel", url: "https://i.postimg.cc/cdGJYXMW/file-20210923-19-147cx5x.jpg", alias: []},
        {category: "person", name: "Greta Thunberg", url: "https://i.postimg.cc/HdXYpbGh/original.jpg", alias: []},
        {category: "person", name: "Michel Platini", url: "https://i.postimg.cc/WjJjn041/Michel-Platini-2010-cropped.jpg", alias: []},
        {category: "person", name: "Christopher Columbus", url: "https://i.postimg.cc/6BpmHNhf/1200px-Portrait-of-a-Man-Said-to-be-Christopher-Columbus.jpg", alias: []},
        {category: "person", name: "Bruce Lee", url: "https://i.postimg.cc/2mHvQRVD/Bruce-Lee-nunchucks.jpg", alias: []},
        {category: "person", name: "Paris Hilton", url: "https://i.postimg.cc/1yFq18Mm/Headshot-Harrington-Tim-Cropped2.jpg", alias: []},
        {category: "person", name: "Keanu Reeves", url: "https://i.postimg.cc/qkkyckXp/1597382622-7037015-sunfm-Keanu-reeves.jpg", alias: []},
        {category: "person", name: "John Travolta", url: "https://i.postimg.cc/p2X5hsRT/9238c1c1a8a56fe5a35a309120af5166.jpg", alias: []},
        {category: "person", name: "Amber Heard", url: "https://i.postimg.cc/D7dnkFVJ/Getty-Images-1240298806.jpg", alias: []},
        {category: "person", name: "Eddie Murphy", url: "https://i.postimg.cc/Ph3C9Wbs/eddie-murphy-9418676-2-402.jpg", alias: []},
        {category: "person", name: "Charlie Chaplin", url: "https://i.postimg.cc/hKFTZ8g4/MV5-BNDcw-MDc0-ODAz-OF5-BMl5-Ban-Bn-Xk-Ft-ZTgw-NTY2-OTI1-MDE-V1-UY1200-CR73-0-630-1200-AL.jpg", alias: []},
        {category: "person", name: "Julius Ceasar", url: "https://i.postimg.cc/3rRF73bK/240px-Retrato-de-Julio-C-sar-26724093101-cropped.jpg", alias: []},
        {category: "person", name: "Mother Theresa", url: "https://i.postimg.cc/FNw2KK5C/800px-Mother-Teresa-1.jpg", alias: []},
        {category: "person", name: "Madonna", url: "https://i.postimg.cc/ys3b2zgm/madonna.jpg", alias: []},
        {category: "person", name: "Rowan Atkinson", url: "https://i.postimg.cc/y7zv53zK/Rowan-Atkinson.jpg", alias: []},
        {category: "person", name: "Mariah Carey", url: "https://i.postimg.cc/LmR3vdz6/Mariah-Carey-WBLS-2018-Interview-2.jpg", alias: []},
        {category: "person", name: "Ludwig van Beethoven", url: "https://i.postimg.cc/nHhYbvRy/640px-Beethoven.jpg", alias: ["Beethoven"]},
        {category: "person", name: "Lil Uzi Vert", url: "https://i.postimg.cc/bpRtyZtp/00-promo-lil-uzi-vert.jpg", alias: []},
        {category: "person", name: "Chuck Norris", url: "https://i.postimg.cc/0P9zB9H3/m-img-24826.jpg", alias: []},
        {category: "painting", name: "The Mona Lisa", url: "https://i.postimg.cc/MzgcpVdM/140430-mona-lisa-mn-741.jpg", alias: []},
        {category: "person", name: "Conor McGregor", url: "https://media.bleacherreport.com/image/upload/c_fill,g_faces,w_1600,h_1600,q_95/v1645830247/gxuwsaqpl9o1qkxh0gkr.jpg", alias: []},
        {category: "movie", name: "Saw", url: "https://i.postimg.cc/4XgjtNw8/SAW-Puppet.jpg", alias: []},
        {category: "movie", name: "Annabelle", url: "https://i.postimg.cc/ChSQBvNz/Annabelle-film-poster.jpg", alias: []},
        {category: "movie", name: "Seven", url: "https://i.postimg.cc/FmDHK8Zk/b45f72ea281f017acd2348fbe6b63d09.jpg", alias: []},
        {category: "movie", name: "The Wizard of Oz", url: "https://i.postimg.cc/ysspLr4j/The-Tin-Man-Cowardly-Lion-Wizard-of.webp", alias: []},
        {category: "movie", name: "The Shawshank Redemption", url: "https://i.postimg.cc/ty5N4qwd/MV5-BNTYx-OTYy-Mz-E3-NV5-BMl5-Ban-Bn-Xk-Ft-ZTcw-OTMx-NDY3-Mw-V1.jpg", alias: []},
        {category: "movie", name: "The Pianist", url: "https://i.postimg.cc/J1YQMMn7/the-pianist-quiz.jpg", alias: []},
        {category: "movie", name: "The Silence of the Lambs", url: "https://i.postimg.cc/6tS0k989/8-2-e1557235193201.png", alias: []},
        {category: "movie", name: "Fight Club", url: "https://i.postimg.cc/c0gxxmLQ/Baker-Fight-Club.jpg", alias: []},
        {category: "movie", name: "Good Will Hunting", url: "https://i.postimg.cc/CSXKk2QP/image.jpg", alias: []},
        {category: "movie", name: "Taxi Driver", url: "https://i.postimg.cc/BZ3VrJbY/EI1-XAq-RW4-AAARx-R.jpg", alias: []},
        {category: "movie", name: "Gladiator", url: "https://i.postimg.cc/b8L77201/2727.webp", alias: []},
        {category: "movie", name: "Die Hard", url: "https://i.postimg.cc/66sfScjB/171526.jpg", alias: []},
        {category: "movie", name: "Mary Poppins", url: "https://i.postimg.cc/dwZLDvVN/mary-poppins-5.jpg", alias: []},
        {category: "object", name: "Bowling ball", url: "https://i.postimg.cc/Ch3dVDMw/1200px-Bowlingball.jpg", alias: []},
        {category: "object", name: "Football", url: "https://i.postimg.cc/0kdh81Pr/Getty-Images-1237679853-e1649181927440.jpg", alias: []},
        {category: "object", name: "Water bottle", url: "https://i.postimg.cc/VfRZx9WC/45.jpg", alias: []},
        {category: "object", name: "Paint", url: "https://i.postimg.cc/NQkN97ZP/05246655.jpg", alias: []},
        {category: "object", name: "Hairbrush", url: "https://i.postimg.cc/FFXcVwLb/71-C-f-UAXRAL-SL1500.jpg", alias: ["Brush"]},
        {category: "object", name: "Lipstick", url: "https://i.postimg.cc/2zmSTmcS/77222634.jpg", alias: []},
        {category: "object", name: "Book", url: "https://i.postimg.cc/8pmKWdFC/book-181404689-1000.jpg", alias: []},
        {category: "object", name: "Anchor", url: "https://i.postimg.cc/PH0YzvbX/Anchor.jpg", alias: []},
        {category: "object", name: "Plate", url: "https://i.postimg.cc/D2Xy20S6/plate-535150495-1000.jpg", alias: []},
        {category: "object", name: "Bowl", url: "https://i.postimg.cc/CFV9qxvm/image.jpg", alias: []},
        {category: "object", name: "Bed", url: "https://i.postimg.cc/08jK7DVC/image.jpg", alias: []},
        {category: "object", name: "Lightbulb", url: "https://i.postimg.cc/dsMdvD9m/image.webp", alias: []},
        {category: "object", name: "Envelope", url: "https://i.postimg.cc/GdWnrCyJ/z3ts0gt81anmc7hk0b0kppjjbgl.jpg", alias: []},
        {category: "object", name: "Stapler", url: "https://i.postimg.cc/p2G3ybSd/image.jpg", alias: []},
        {category: "object", name: "Power drill", url: "https://i.postimg.cc/9m8V3gT6/2020-m0014-m007-m050-asym-m008-m022-drillguide-combidrill-9147964-max-W-1200-qlt-75-fmt.jpg", alias: ["Drill"]},
        {category: "object", name: "Hammer", url: "https://i.postimg.cc/XVgB53S9/image.jpg", alias: []},
        {category: "object", name: "Nail", url: "https://i.postimg.cc/jxX1BWVC/09458802.webp", alias: []},
        {category: "object", name: "Cane", url: "https://i.postimg.cc/CFSPVjGY/R-10372-CN-BI-03-2000x.jpg", alias: ["Walking Cane"]},
        {category: "weapon", name: "Sword", url: "https://i.postimg.cc/74dmX85S/Studio-Session-1232.jpg", alias: []},
        {category: "weapon", name: "Bow", url: "https://i.postimg.cc/BsD9BCnQ/OMP19916035.jpg", alias: []},
        {category: "object", name: "Bullet", url: "https://i.postimg.cc/VYRB8pgL/image.jpg", alias: []},
        {category: "weapon", name: "Spear", url: "https://i.postimg.cc/DFXMLyy9/Spear.jpg", alias: []},
        {category: "object", name: "Tape", url: "https://i.postimg.cc/VzsXFD1x/Adhesive-tapes-clear.jpg", alias: []},
        {category: "element", name: "Gold", url: "https://i.postimg.cc/pV6yYYZH/closeup-of-big-gold-nugget-511603038-5ad92a97fa6bcc00362b919b.jpg", alias: []},
    ],
    hard: [
        {category: "object", name: "Box cutter", url: "https://i.postimg.cc/Q8hWywmj/stanley-utility-knives-10-099-c3-600.webp", alias: []},
        {category: "object", name: "Anvil", url: "https://i.postimg.cc/tp9GgjRh/il-fullxfull-2204414276-int4.jpg", alias: []},
        {category: "material", name: "Carbon Fiber", url: "https://i.postimg.cc/RS30Cnmp/Carbon-Fiber-Illustration.jpg", alias: []},
        {category: "person", name: "Elton John", url: "https://i.postimg.cc/9X7nqNPv/Elton-John-Cannes-2019.jpg"},
        {category: "architecture", name: "Veranda", url: "https://i.postimg.cc/yYTnmqDr/1200px-Grande-Verandah.jpg"},
        {category: "TV Show", name: "Better Call Saul", url: "https://i.postimg.cc/SKGyqxRf/better-call-saul-y-como-el-final-se-revela-en-breaking-bad.jpg"},
        {category: "country", name: "Kazakhstan", url: "https://i.postimg.cc/6prKLprx/1000px-Flag-of-Kazakhstan-svg.png"},
        {category: "operating system", name: "Ubuntu", url: "https://i.postimg.cc/d11KYRzJ/1200px-Logo-ubuntu-cof-orange-hex-svg.png"},
        {category: "movie", name: "1984", url: "https://i.postimg.cc/fLZftBwh/Rosen-1984.jpg"},
        {category: "app", name: "Facebook Messenger", url: "https://i.postimg.cc/GmTt2vNQ/image.jpg"},
        {category: "person", name: "Malala Yousafzai", url: "https://i.postimg.cc/3rktj599/Malala-Yousafzai-cropped.jpg"},
        {category: "programming language", name: "Ruby", url: "https://i.postimg.cc/L6PXd547/flat-750x1000-075-f-u6.jpg"},
        {category: "programming language", name: "Scala", url: "https://i.postimg.cc/NMWKTHf6/scala-490x490.webp"},
        {category: "person", name: "Lewis Hamilton", url: "https://i.postimg.cc/1z8RH3dJ/640px-Lewis-Hamilton-2016-Malaysia-2.jpg"},
        {category: "person", name: "Max Verstappen", url: "https://i.postimg.cc/8ctx9hJW/XPB-1126234-Hi-Res.jpg"},
        {category: "person", name: "Sandra Bullock", url: "https://i.postimg.cc/m21S0YHs/image.jpg"},
        {category: "game", name: "Detroit Become Human", url: "https://i.postimg.cc/hGv1g6yf/1280x720.jpg"},
        {category: "animal", name: "Axolotl", url: "https://i.postimg.cc/0yn1hMF9/baby-axolotl.jpg"},
        {category: "anime", name: "Yu-Gi-Oh", url: "https://i.postimg.cc/pxmyD9FW/yugioh.jpg"},
        {category: "anime", name: "Violet Evergarden", url: "https://i.postimg.cc/qkKjhBxj/MV5-BYTJm-Nzc5-YTEt-NTBm-Ny00-Ym-Ux-LWFl-Nzkt-Yj-Zj-MTg3-OGY3-ZDhk-Xk-Ey-Xk-Fqc-Gde-QXVy-Mz-Uz-Mzgx-NA-V1.jpg"},
        {category: "anime", name: "Cowboy Bebop", url: "https://i.postimg.cc/tXb26Qvb/image-w1280.jpg"},
        {category: "anime", name: "Jujutsu Kaisen", url: "https://i.postimg.cc/WTJnfbQj/NEOBK-2655364.jpg"},
        {category: "anime", name: "Fullmetal Achemist", url: "https://i.postimg.cc/HdxGJ5cz/e4aec5405948deb11aac1373e81dd72e.jpg"}, //fullmetal(-)//
        {category: "anime", name: "Your Lie in April", url: "https://i.postimg.cc/HYhNXv7t/image.jpg"},
        {category: "anime", name: "Porco Rosso", url: "https://i.postimg.cc/sVZG3v4D/image.jpg"},
        {category: "cartoon", name: "The Loud House", url: "https://i.postimg.cc/cZWtN1g0/1200x675mf.jpg"},
        {category: "cartoon", name: "PJ Masks", url: "https://i.postimg.cc/2mTyRQN7/MV5-BYj-Rk-Mjk4-Mjgt-ODc4-ZS00-YTFj-LWEz-MTMt-M2-I1-ZWI5-Zm-Nm-ZDMx-Xk-Ey-Xk-Fqc-Gde-QXVy-ODg0-NDE2-NTI-V1.jpg"},
        {category: "cartoon", name: "Inspector Gadget", url: "https://i.postimg.cc/2CLSZgb0/MV5-BMTY0-Nzgy-OTQ2-MV5-BMl5-Ban-Bn-Xk-Ft-ZTgw-OTcz-Nj-E4-MTI-V1.jpg"},
        {category: "cartoon", name: "Asterix", url: "https://i.postimg.cc/csQ1DYcY/l064-7.png"},
        {category: "cartoon", name: "Sonic X", url: "https://i.postimg.cc/zz8z4BdQ/image-w1280.jpg"}, 
        {category: "cartoon", name: "Winx Club", url: "https://i.postimg.cc/mBJbBVXC/p186546-ce-h9-aa.jpg"},
        {category: "cartoon", name: "Teen Titans", url: "https://i.postimg.cc/V1NrNGRV/p19815096-i-v13-ab.jpg"},
        {category: "TV Show", name: "Parks and Recreation", url: "https://i.postimg.cc/NgYLvpFb/rs-600x600-200429084749-600-parks-and-rec-ch-042920.webp"},
        {category: "TV Show", name: "Ted Lasso", url: "https://i.postimg.cc/cxPS0LTZ/url-https-california-times-brightspot-s3-amazonaws-com-c4-31-be85d8e64f8880c50feecc6b694d-ted-las.jpg"},
        {category: "TV Show", name: "Saved by the Bell", url: "https://i.postimg.cc/Bs2yXpn2/ustv-saved-by-the-bell-season-1.jpg"},
        {category: "TV Show", name: "All of us are dead", url: "https://i.postimg.cc/2kGZKgx4/All-Of-Us-Are-Dead.jpg"},
        {category: "TV Show", name: "My Name", url: "https://i.postimg.cc/92bbSk08/04-myname-unit-002-1634743404.jpg"},
        {category: "TV Show", name: "Ozark", url: "https://i.postimg.cc/8DT3fWJ3/ozark-season-4-review.jpg"},
        {category: "TV Show", name: "Vicenzo", url: "https://i.postimg.cc/zz2c12zg/MV5-BYWIw-YTg2-Y2-Yt-Yz-Ew-Ny00-Y2-Y0-LWFk-Zjkt-Nj-Bl-MWZh-NDY2-NGE0-Xk-Ey-Xk-Fqc-Gde-QXVy-NDY5-Mj-My-NTg-V1.jpg"},
        {category: "TV Show", name: "The Irishman", url: "https://i.postimg.cc/KZzWsyF2/MV5-BMGUy-M2-Zi-Zm-Ut-MWY0-OC00-NTQ4-LThk-OGUt-Nj-Y2-Njkz-MDJi-MWMw-Xk-Ey-Xk-Fqc-Gde-QXVy-Mz-Y0-MTE3-Nz-U-V1.jpg"},
        {category: "animal", name: "Hornet", url: "https://i.postimg.cc/hc2ynL7L/5c5ab2c4-6b7c-48de-8237-0e3397938352-large1x1-vlcsnap2020050610h16m25s768.png"},
        {category: "animal", name: "Beluga", url: "https://i.postimg.cc/GrTvx38C/beluga-whale-webcam-9.jpg"},
        {category: "animal", name: "Fennec Fox", url: "https://i.postimg.cc/2mvJ1DxH/62697a8dbb0bd-preview.jpg"},
        {category: "animal", name: "Salamander", url: "https://i.postimg.cc/X3bqP9QQ/fire-salamander.jpg"},
        {category: "animal", name: "Pelican", url: "https://i.postimg.cc/cZcsv20N/photo-1579109191035-dfa9544f8be1-ixlib-rb-1-2.jpg"},
        {category: "animal", name: "Vulture", url: "https://i.postimg.cc/9V7H5kNh/vulture-hooded-Moru-SNP-POliver-2017-02.jpg"},
        {category: "person", name: "Elizabeth 1", url: "https://i.postimg.cc/6wbVn9rr/queen-elizabeth-i-photo-by-ann-ronan-picturesprint-collectorgetty-images.jpg", alias: ["Elizabeth", "Elizabeth Tudor"]}, // Elizabeth (-), same points if Elizabeth Tudor (=)//
        {category: "person", name: "Napoleon Bonaparte", url: "https://i.postimg.cc/JrYLRy9Y/image.png", alias: ["Napoleon"]}, //Napoleon (-)//
        {category: "person", name: "Stormzy", url: "https://i.postimg.cc/HHc7ybB2/image.jpg"},
        {category: "person", name: "Andrew Tate", url: "https://i.postimg.cc/2rdMFcwF/image.png"},
        {category: "person", name: "Shaquille O'neal", url: "https://i.postimg.cc/vb9gP9gv/6bb16-15398694878129-800.jpg"},
        {category: "person", name: "Steven Spielberg", url: "https://i.postimg.cc/Sy5mFTHY/t-Zxcg19-YQ3e8f-J0p-Os7hjlnmmr6.jpg"},
        {category: "person", name: "Floyd Mayweather Jr.", url: "https://i.postimg.cc/0P63h5Pn/21-BOXING1-1424480903046-article-Large.jpg"},
        {category: "person", name: "Nikola Tesla", url: "https://i.postimg.cc/8TcC26s3/gettyimages-666932578.jpg"},
        {category: "person", name: "Kevin Durant", url: "https://i.postimg.cc/xf2n1JT9/Kevin-Durant-Wizards-v-Warriors-1-24-2019-cropped.jpg"},
        {category: "app", name: "Visual Studio Code", url: "https://i.postimg.cc/KZZyXX9Y/f7284e4eebc41b5fa9112954787eb4f7.png"},
        {category: "app", name: "WeChat", url: "https://i.postimg.cc/TG5F4YR9/image.jpg"},
        {category: "app", name: "KakaoTalk", url: "https://i.postimg.cc/5xkKsDTT/kakaotalk.jpg"},
        {category: "brand", name: "Nokia", url: "https://i.postimg.cc/dwKHN2Ns/51-I0-Sh-KUt-L-AC.jpg"},
        {category: "brand", name: "FedEx", url: "https://i.postimg.cc/hKN7MrMM/Fed-Ex-Dollar-General.jpg"},
        {category: "brand", name: "Bugatti", url: "https://i.postimg.cc/xnDfsZSX/se-image-c4a9cdcf0a58353aa5323d397bde7f34.jpg"},
        {category: "brand", name: "HSBC", url: "https://i.postimg.cc/KG3bfPq7/AFP-9-CH9-KK-1624290880390-1624290894160.webp"},
        {category: "brand", name: "Nickelodeon", url: "https://i.postimg.cc/YrYVjbDP/ll01vtvpkovhzxhaxj3e.jpg"},
        {category: "country", name: "Democratic Republic of the Congo", url: "https://i.postimg.cc/KF4f995h/drc.jpg"},
        {category: "country", name: "Madagascar", url: "https://i.postimg.cc/jt0fzvgX/shutterstock-1115155292.jpg"},
        {category: "country", name: "Kuweit", url: "https://i.postimg.cc/kqgmhPpX/1374113299901971720.jpg"},
        {category: "country", name: "Qatar", url: "https://i.postimg.cc/Smq8xswm/photo-1646207795621-733fe1646f9b-ixlib-rb-1-2.jpg"},
        {category: "country", name: "Iceland", url: "https://i.postimg.cc/4X4Q9By0/8463bc981454101466bdc841bd2c890c.jpg"},
        {category: "country", name: "Wales", url: "https://i.postimg.cc/44Z9Txh0/Hba47271cc96b4293acc04a02b0b2464d-L.jpg"},
        {category: "country", name: "Singapore", url: "https://i.postimg.cc/L9kJvF03/singapore-flag-std-1.jpg"},
        {category: "game", name: "Dark Souls", url: "https://i.postimg.cc/mbL07Hh8/maxresdefault.jpg"},
        {category: "game", name: "Stardew Valley", url: "https://i.postimg.cc/gkN0cmDG/maxresdefault.jpg"},
        {category: "game", name: "Counter Strike: Global Offensive", url: "https://i.postimg.cc/Tfc0gHmv/Counter-Strike-Global-Offensive-5.webp", alias: ["Counter Strike", "CSGO", "CS:GO"]},
        {category: "game", name: "Garry's Mod", url: "https://i.postimg.cc/7Dn0WJLg/steamaltergifteu-key-name-eu-steam-altergift-large.png"},
        {category: "game", name: "Terraria", url: "https://i.postimg.cc/gdm68cKr/138083434951.jpg"},
        {category: "game", name: "Factorio", url: "https://i.postimg.cc/1R2Rn8Q5/Screen-Shot-2018-10-03-at-5-25-28-PM.png"},    
        {category: "game", name: "Nintendogs", url: "https://i.postimg.cc/PHKpLTYd/WWSM-Nintendogs.png"},
        {category: "movie", name: "There Will be Blood", url: "https://i.postimg.cc/Sy14hTYb/e5bfea18f0da8ab9e802743841a6c8c6.jpg"},
        {category: "movie", name: "Goodfellas", url: "https://i.postimg.cc/Mq08TKfD/220526-ray-liotta-al-1218-332f49.jpg"},
        {category: "movie", name: "12 Angry Men", url: "https://i.postimg.cc/6W4kN9NC/EB20020929-REVIEWS08209290301-AR.jpg"},
        {category: "movie", name: "Apu", url: "https://i.postimg.cc/p24SCgnr/apu2.png"},
        {category: "movie", name: "Parasite", url: "https://i.postimg.cc/GbSg3ZKK/image.jpg"},
        {category: "movie", name: "Reservoir Dogs", url: "https://i.postimg.cc/9Vtxw41r/Shone-Reservoir-Dogs.jpg"},
        {category: "object", name: "Router", url: "https://i.postimg.cc/vQX01hxH/asus-rt-ax53u-wifi-6-router-12.jpg"},
        {category: "object", name: "Cheese Grater", url: "https://i.postimg.cc/wH4n4qvT/idealisk-grater-stainless-steel-0713134-pe729282-s5.webp"},
        {category: "object", name: "Aluminum Foil", url: "https://i.postimg.cc/wHQt8rNr/1444835089119.jpg"},
        {category: "object", name: "Saddle", url: "https://i.postimg.cc/xYLN1hSY/all-purpose-pad-navy-on-saint-web.png"},
        {category: "object", name: "Spurs", url: "https://i.postimg.cc/yV53Dzd6/518q8-Ee-Cax-L-AC-SS450.jpg"},
        {category: "object", name: "Lint Roller", url: "https://i.postimg.cc/w6FFZM0f/2311056.jpg"},
        {category: "person", name: "Frank Sinatra", url: "https://i.postimg.cc/jKB4Bnr5/gettyimages-119684687.jpg", alias: []},
        {category: "person", name: "Rosa Parks", url: "https://i.postimg.cc/Jrvjwvvg/2-wordpress-Rosa-Parks-Booking.jpg", alias: []},
        {category: "person", name: "George Orwell", url: "https://i.postimg.cc/fWQkfN6w/image.jpg", alias: []},
        {category: "person", name: "Vladimir Lenin", url: "https://i.postimg.cc/Lm2C0gzP/6066256715e9f95b7660da8e.jpg", alias: ["Lenin"]},
        {category: "person", name: "Sigmund Freud", url: "https://i.postimg.cc/7wMX7PpZ/Pomerantz-Freud.jpg", alias: []},
        {category: "person", name: "Stevie Wonder", url: "https://i.postimg.cc/Xjd9bQWY/stevie-wonder-medium.jpg", alias: []},
        {category: "person", name: "Queen Victoria", url: "https://i.postimg.cc/GbtY2cRN/Queen-Victoria-by-Bassano.jpg", alias: []},
        {category: "person", name: "Leonardo Da Vinci", url: "https://i.postimg.cc/Zb8vgnP9/01-leonardo-da-vinci-book-talk-2x3.webp", alias: []},
        {category: "person", name: "Mao Zedong", url: "https://i.postimg.cc/ysg34LT4/gettyimages-527191268-copy.jpg", alias: []},
        {category: "person", name: "Xi Jinping", url: "https://i.postimg.cc/k9DBKTz6/Xi-Jinping-2019.jpg", alias: []},
        {category: "person", name: "Dalai Lama", url: "https://i.postimg.cc/rMrsYK8q/14th-Dalai-Lama-2008.jpg", alias: []},
        {category: "person", name: "Channing Tatum", url: "https://i.postimg.cc/hK8jc6zw/channing-waxxx.webp", alias: []},
        {category: "person", name: "Damon Wayans", url: "https://i.postimg.cc/4ZCxHX6M/554329.jpg", alias: []},
        {category: "person", name: "Quentin Tarantino", url: "https://i.postimg.cc/0kK12KXQ/Quentin-Tarantino-2020.jpg", alias: []},
        {category: "person", name: "Tim Burton", url: "https://i.postimg.cc/0PfFvC5n/tim-burton-9542431-1-402.jpg", alias: []},
        {category: "person", name: "Alfred Hitchcock", url: "https://i.postimg.cc/MWj9n0wh/MV5-BMTQx-OTg3-ODc2-NV5-BMl5-Ban-Bn-Xk-Ft-ZTYw-NTg0-NTU2-V1.jpg", alias: []},
        {category: "person", name: "Joan of Arc", url: "https://i.postimg.cc/J1cBYt5s/John-Everett-Millais-Joan-of-Arc.jpg", alias: []},
        {category: "person", name: "Jane Austen", url: "https://i.postimg.cc/FNCtcZtR/Jane-Austen-Cassandra-engraving-portrait-1810.jpg", alias: []},
        {category: "person", name: "Charles Dickens", url: "https://i.postimg.cc/CYJ9TNxN/charles-dickens-10.jpg", alias: []},
        {category: "movie", name: "Inception", url: "https://i.postimg.cc/X35860xX/inception-film-1.jpg"},
        {category: "person", name: "Tutankhamen", url: "https://i.postimg.cc/fZWgK9f0/Tutankhamen-mask-tomb-king-Egyptian-Museum-Cairo.jpg", alias: []},
        {category: "person", name: "Michelangelo", url: "https://i.postimg.cc/J1WpBDh0/640px-Michelangelo-Daniele-da-Volterra-dettaglio.jpg", alias: []},
        {category: "person", name: "Claude Monet", url: "https://i.postimg.cc/NB33p0Mq/Claude-Monet-1899-Nadar-crop.jpg", alias: []},
        {category: "person", name: "Che Guevara", url: "https://i.postimg.cc/7xYmVvgr/0621017-che-guevara.jpg", alias: []},
        {category: "person", name: "Stephen Hawking", url: "https://i.postimg.cc/gdSdqd8m/hawking-page.png", alias: []},
        {category: "movie", name: "Get Out", url: "https://i.postimg.cc/dJjBNgT6/699e2c65f9c92ff77154a1b2909b3eaf6b-17-get-out-review-2x-h473-w710.jpg", alias: []},
        {category: "movie", name: "Rec", url: "https://i.postimg.cc/kn5x1GCM/image.webp", alias: []},
        {category: "movie", name: "Bird Box", url: "https://i.postimg.cc/KGM3wgHb/00-story-bird-box.jpg", alias: []},
        {category: "movie", name: "The Conjuring", url: "https://i.postimg.cc/PfHJ7VDb/1503998712-conjuring-2-publicity-still-2-h-2016.jpg", alias: []},
        {category: "movie", name: "American Beauty", url: "https://i.postimg.cc/xQ4YBswy/image.jpg", alias: []},
        {category: "movie", name: "The Shining", url: "https://i.postimg.cc/JMRTx8pT/55893-warner-home-video3-0fec54aced70e3ad8b2c4df2acd9f716.jpg", alias: []},
        {category: "movie", name: "Psycho", url: "https://i.postimg.cc/DvHSZ787/Psycho-1.jpg", alias: []},
        {category: "movie", name: "Saving Private Ryan", url: "https://i.postimg.cc/mT1zvzD8/WhzWFv6.png", alias: []},
        {category: "movie", name: "The Usual Suspects", url: "https://i.postimg.cc/hDs1XzVV/usual-suspects-line-up-1000.jpg", alias: []},
        {category: "movie", name: "The Big Lobowsky", url: "https://i.postimg.cc/66szJJVm/lebowski-main.jpg", alias: []},
        {category: "movie", name: "Braveheart", url: "https://i.postimg.cc/SqDjv7yW/braveheart.jpg", alias: []},
        {category: "movie", name: "Slumdog Millionaire", url: "https://i.postimg.cc/HmPk0W32/MV5-BMTMx-NTIy-Nz-Y4-OF5-BMl5-Ban-Bn-Xk-Ft-ZTcw-NTg0-ODEz-Mg-V1.jpg", alias: []},
        {category: "mechanism", name: "Parking brake", url: "https://i.postimg.cc/bzZ5228X/Driver-Pulling-Emergency-Brake-1636649343318.jpg", alias: ["Handbrake", "Emergency Brake"]},
    ],
}