module.exports = {
    easy: [
        {category: "cartoon", name: "Rick and Morty", url: "https://i.postimg.cc/xC7BVwvP/rick-and-morty-watch-i50046.jpg"},
        {category: "person", name: "Barack Obama", url: "https://i.postimg.cc/ZKnvMrWx/Official-portrait-of-Barack-Obama-cropped.jpg"},
        {category: "furniture", name: "Chair", url: "https://i.postimg.cc/x8RG3YFj/Chair-1.jpg"},
        {category: "TV Show", name: "Breaking Bad", url: "https://i.postimg.cc/Y0m86JBh/HD-wallpaper-breaking-bad-brba-breaking-bad-season-3-heisenberg-jesse-pinkman-sky-walter-white.jpg"},
        {category: "country", name: "The United States of America", url: "https://i.postimg.cc/g08Y70yD/close-up-shot-of-an-american-flag-3e3eee-1600.jpg"},
        {category: "app", name: "TikTok", url: "https://i.postimg.cc/t4DQfV8p/tiktok-icon2.png"},
        {category: "game", name: "Fortnite", url: "https://i.postimg.cc/wvt4TtMK/1207.webp"},
        {category: "person", name: "Donald Trump", url: "https://i.postimg.cc/xT9rgChY/Donald-Trump-by-Gage-Skidmore.jpg"},
        {category: "animal", name: "Dog", url: "https://i.postimg.cc/6pdLkXHt/image.jpg"},
        {category: "animal", name: "Cat", url: "https://i.postimg.cc/fWx1DJ80/photo-1529778873920-4da4926a72c2-ixlib-rb-1-2.jpg"},
        {category: "brand", name: "Ferrari", url: "https://i.postimg.cc/bJx5JCfk/logo-Ferrari.jpg"},
        {category: "planet", name: "Jupiter", url: "https://i.postimg.cc/cHqCq6LJ/28284959668-650c93fb69-b.jpg"},
        {category: "monument", name: "The Eiffel Tower", url: "https://i.postimg.cc/0jKrhmpr/Eiffel-tower-paris-france.jpg"},
        {category: "object", name: "Map", url: "https://i.postimg.cc/wjwyy6Tq/pexels-photo-1252500.jpg"},
        {category: "app", name: "Twitter", url: "https://i.postimg.cc/Pf1CbbrF/social-media-twitter-logo-blue-isolated-free-vector.jpg"},
        {category: "app", name: "Instagram", url: "https://i.postimg.cc/MHYZCDn6/instagram-icon-1057-2227.webp"},
        {category: "game", name: "Stardew Valley", url: "https://i.postimg.cc/gkN0cmDG/maxresdefault.jpg"},
        {category: "game", name: "Street Fighter", url: "https://i.postimg.cc/13xhGdML/5-1-1-1.jpg"},
        {category: "animal", name: "Monkey", url: "https://i.postimg.cc/d36Rs3n8/monkey-bananav3.jpg"},
        {category: "animal", name: "Gorilla", url: "https://i.postimg.cc/05hZNK8C/15452888118-d1f36db7fb-b.jpg"},
        {category: "country", name: "France", url: "https://i.postimg.cc/QCDzHBDC/285049-2022x1348-french-flag-in-paris.jpg"},
        {category: "character", name: "Darth Vader", url: "https://i.postimg.cc/X7x4wWpX/32461333995-087c9243f1-b.jpg"},
        {category: "object", name: "Nail clippers", url: "https://i.postimg.cc/Sx8dBSCx/Nailclippers3.jpg"},
        {category: "object", name: "Fork", url: "https://i.postimg.cc/85nLF9MY/35244123291-a9a9ba6f0c-b.jpg"},
        {category: "object", name: "Spoon", url: "https://i.postimg.cc/rpx2hR8y/1733617229-a77bfacb6d-c.jpg"},
        {category: "person", name: "Martin Luther King Jr.", url: "https://i.postimg.cc/FKnBm9Dd/Martin-luther-king-2-cropped.jpg"},
        {category: "animal", name: "Rabbit", url: "https://i.postimg.cc/vZBV69WK/87132-2x3.webp"},
        {category: "animal", name: "Guinea Pig", url: "https://i.postimg.cc/6pgy2P67/Basic-Guinea-Pig-Care.jpg"},
        {category: "animal", name: "Elephant", url: "https://i.postimg.cc/xTW2KVHS/6987533681-2112daf5ea-b.jpg"},
        {category: "animal", name: "Zebra", url: "https://i.postimg.cc/qqzP31vR/plains-zebra-thumb-3x4.webp"},
        {category: "animal", name: "Giraffe", url: "https://i.postimg.cc/76QcwSny/pexels-photo-6404790.jpg"},
        {category: "animal", name: "Tiger", url: "https://i.postimg.cc/HWrW52KX/Medium-WW226367.jpg"},
        {category: "animal", name: "Koala", url: "https://i.postimg.cc/0y09xHMR/Some-image-width-800-25af59c.jpg"},
        {category: "animal", name: "Bald Eagle", url: "https://i.postimg.cc/fTxNjgvt/Bald-eagle-Adult.jpg"},
        {category: "animal", name: "Snake", url: "https://i.postimg.cc/7ZYWGBty/How-to-Avoid-Snakes-Slithering-Up-Your-Toilet-shutterstock-780480850-1.jpg"},
        {category: "animal", name: "Dolphin", url: "https://i.postimg.cc/RFrdRGdh/Dolphin-fasting.jpg"},
        {category: "animal", name: "Kangaroo", url: "https://i.postimg.cc/5NtB8ZJp/1928593646-7d234c9f28-b.jpg"},
        {category: "animal", name: "Bear", url: "https://i.postimg.cc/Bnr29bKw/2010-brown-bear.jpg"},
        {category: "movie ", name: "Star Wars", url: "https://i.postimg.cc/zXmjYdYk/hero-the-history-of-star-wars-movies.jpg"},
        {category: "animal", name: "Owl", url: "https://i.postimg.cc/hvLGH4VT/1200px-Bubo-virginianus-06.jpg"},
        {category: "animal", name: "Horse", url: "https://i.postimg.cc/9zHWp6S0/photo-1598974357801-cbca100e65d3-ixlib-rb-1-2.jpg"},
        {category: "animal", name: "Donkey", url: "https://i.postimg.cc/Sxps79Fd/World-Donkey-Day-jpg.webp"},
        {category: "animal", name: "Duck", url: "https://i.postimg.cc/cHz27fjL/Male-mallard-duck-2.jpg"},
        {category: "animal", name: "Goat", url: "https://i.postimg.cc/5Nzd3kfd/Hausziege-04.jpg"},
        {category: "planet", name: "Mars", url: "https://i.postimg.cc/zBpW4j5q/mars.jpg"},
        {category: "planet", name: "Saturn", url: "https://i.postimg.cc/G3JSmw3p/image.jpg"},
        {category: "anime", name: "Naruto Shippuden", url: "https://i.postimg.cc/qMfpCsgL/naruto-shippuden-anime.jpg"},//Naruto can work less points ill add this sign (-)//
        {category: "anime", name: "Death Note", url: "https://i.postimg.cc/7YPhwQrN/image.jpg"},
        {category: "anime", name: "My Hero Academia", url: "https://i.postimg.cc/pX9NfDfH/5121872-043974e0-8c3c-42fb-95f1-11b11c3a3a30.jpg"},
        {category: "anime", name: "One Punch Man", url: "https://i.postimg.cc/FFd2VKvC/affiche-370x0.jpg"},
        {category: "anime", name: "Your Name", url: "https://i.postimg.cc/brgQdDvV/image.jpg"},
        {category: "anime", name: "Howl's Moving Castle", url: "https://i.postimg.cc/RF6SNjVk/il-570x-N-2710747754-8ayc.webp"},
        {category: "cartoon", name:"The Simpsons", url: "https://i.postimg.cc/kGGx6Mtn/fox-the-simpsons-1420x798.jpg"},
        {category: "cartoon", name: "Paw Patrol", url: "https://i.postimg.cc/jSc372Df/1200x675mf.jpg"},
        {category: "cartoon", name: "Tom and Jerry", url: "https://i.postimg.cc/wv4dcF3h/37c2eee04ebc3b45d27003352e82acf0-wallpaper-for-phone-cartoon-wallpaper.jpg"},
        {category: "person", name: "Joaquin Phoenix", url: "https://i.postimg.cc/DZ48GWwy/LTIy-NDMuan-Bl-Zw.jpg"},
        {category: "person", name: "Taylor Swift", url: "https://i.postimg.cc/fynmR4hL/taylor-swift-3664.jpg"},
        {category: "person", name: "Rihanna", url: "https://i.postimg.cc/52SZb1LP/Rihanna.jpg"},
        {category: "person", name: "Beyonce", url: "https://i.postimg.cc/rm4PKL7R/beyonce-press-2022-cr-parkwood-entertaiment-billboard-1548.jpg"},
        {category: "person", name: "Drake", url: "https://i.postimg.cc/sgqP1HSt/rs-1200x1200-201012052848-1200-Drake-Euphoria-Aubrey-Drake-Graham-ch-101220.jpg"},
        {category: "person", name: "The Weekend", url: "https://i.postimg.cc/tJFPZ93f/rs-1200x1200-210207174748-1200-the-weeknd-super-bowl-2021-ct.webp"},
        {category: "person", name: "Ariana Grande", url: "https://i.postimg.cc/g2ZNWLBy/24-JPGRANDE1-super-Jumbo.jpg"},
        {category: "person", name: "Elon Musk", url: "https://i.postimg.cc/s2pzvX17/1200px-Elon-Musk-Royal-Society-crop2.jpg"},
        {category: "person", name: "Selena Gomez", url: "https://i.postimg.cc/ZRsjF8MN/newFile.jpg"},
        {category: "person", name: "Justin Bieber", url: "https://i.postimg.cc/NMbJ5qtQ/singer-songwriter-justin-bieber-attends-the-2014-young-news-photo-452816022-1543262087.jpg"},
        {category: "person", name: "Cristiano Ronaldo", url: "https://i.postimg.cc/v8XPPRcW/cd559663f19a01c3f2588133067a06ef.jpg"},
        {category: "person", name: "Dwayne Johnson", url: "https://i.postimg.cc/KYrw7Jwj/00-tout-the-rock.jpg"},
        {category: "person", name: "Tom Hanks", url: "https://i.postimg.cc/RhBc1x6J/Tom-hanks.jpg"},
        {category: "person", name: "Eminem", url: "https://i.postimg.cc/JnfGZNFT/eminem-photo-by-dave-j-hogan-getty-images-entertainment-getty-187596325.jpg"},
        {category: "TV Show", name: "The Big Bang Theory", url: "https://i.postimg.cc/yddbc9RS/142694.jpg"},
        {category: "TV Show", name: "Euphoria", url: "https://i.postimg.cc/jj7ynSg4/zendaya-en-euphoria-6862.jpg"},
        {category: "TV Show", name: "The Office", url: "https://i.postimg.cc/1z5HjqHR/office-leaving-netflix.png"},
        {category: "TV Show", name: "Malcolm in the Middle", url: "https://i.postimg.cc/0y9F9rfF/image.jpg"}, //Malcolm (-)//
        {category: "TV Show", name: "Lucifer", url: "https://i.postimg.cc/mkzVS1sX/MV5-BOWFj-Mm-E5-Mzgt-ZTFh-OS00-M2-Uz-LWEy-MGUt-Zj-Ix-ZDFi-Zj-I5-Nj-Qw-Xk-Ey-Xk-Fqc-Gde-QXVy-MTYz-MDM0-NTU-V1.jpg"},
        {category: "TV Show", name: "Squid game", url: "https://i.postimg.cc/W4cH5nWB/5ZHq1PK.png"},
        {category: "animal", name: "Cheetah", url: "https://i.postimg.cc/Kcr6KdYd/23517432926-735329bbcc-b.jpg"},
        {category: "app", name: "WhatsApp", url: "https://i.postimg.cc/Gh6Z8YD5/original.jpg"},
        {category: "app", name: "Steam", url: "https://i.postimg.cc/tJcWC9YL/steam-logo-blurred-background.jpg"},
        {category: "app", name: "Twitch", url: "https://i.postimg.cc/XvZJ49w7/21k-Rx-CJs-UL.png"},
        {category: "brand", name: "Amazon", url: "https://i.postimg.cc/FHk5Kpnq/amazon-600.png"},
        {category: "brand", name: "eBay", url: "https://i.postimg.cc/02s1N7q2/VCT3-V3-ACA5-DI7-A2-QNCC2-GSNOW4.jpg"},
        {category: "brand", name: "BMW", url: "https://i.postimg.cc/mDk28CrG/23bmw1-mobile-Master-At3x.jpg"},
        {category: "brand", name: "Adidas", url: "https://cdn.britannica.com/94/193794-050-0FB7060D/Adidas-logo.jpg"},
        {category: "brand", name: "Nike", url: "https://i.postimg.cc/CLcNBVfr/nike-voguebus-Edward-Berthelot-Getty-Images-feb-21-story.jpg"},
        {category: "brand", name: "Starbucks", url: "https://i.postimg.cc/G2sLYr2F/1481130851-7484.webp"},
        {category: "country", name: "Japan", url: "https://i.postimg.cc/d3pG6JmJ/colton-jones-p8-URGduy-Eg-unsplash-scaled.jpg"},
        {category: "country", name: "Egypt", url: "https://i.postimg.cc/FK6Cfk7K/cairo-egypt-03.jpg"},
        {category: "country", name: "Canada", url: "https://i.postimg.cc/gJQ0BsrP/Canada-Flag-Lake-Louise-1024x683.jpg"},
        {category: "country", name: "China", url: "https://i.postimg.cc/Y2RngP4V/photo-1589889353869-b0c95b307770-ixlib-rb-1-2.jpg"},
        {category: "country", name: "India", url: "https://i.postimg.cc/zDpNB0qD/Indian-National-Flag-What-every-Indian-citizen-must-know.webp"},
        {category: "game", name: "Minecraft", url: "https://i.postimg.cc/gjKtMSkM/c82a607ee93697da806c5263dac3741e-minecraft-account-minecraft-stuff.jpg"},
    ],
    medium: [
        {category: "anime", name: "Spirited Away", url: "https://i.postimg.cc/ydTnvFDz/25007888619-1bc2f8c199-b.jpg"},
        {category: "person", name: "Doja Cat", url: "https://i.postimg.cc/Kz0x40mX/Doja-Cat-Elvis.jpg"},
        {category: "furniture", name: "Coffee table", url: "https://i.postimg.cc/X75QpGW3/ss19-h-frmcof.png"},
        {category: "TV Show", name: "Stranger Things", url: "https://i.postimg.cc/D0FVJXwN/Phillips-Stranger-Things-Kids-S3.jpg"},
        {category: "country", name: "Sweden", url: "https://i.postimg.cc/Jzcx5ft2/1200px-Flag-of-Sweden-svg.png"},
        {category: "brand", name: "PlayStation", url: "https://i.postimg.cc/wBqVfwmT/La-derniere-mise-a-jour-de-Sony-garantit-que-les-1200x1200.jpg"},
        {category: "game", name: "Rocket League", url: "https://i.postimg.cc/LsxVrjtk/rl-home-f2p-launch-cross-square-10016.jpg"},
        {category: "cartoon", name: "My Little Pony", url: "https://i.postimg.cc/hGZwRXTm/290941.jpg"},
        {category: "dog breed", name: "Golden Retriever", url: "https://i.postimg.cc/g0jD1GDx/golden-retriever-dog-breed-info.jpg"},
        {category: "object", name: "Black Hole", url: "https://i.postimg.cc/g04psJL5/49935923702-e808c60963-b.jpg"},
        {category: "object", name: "Water slide", url: "https://i.postimg.cc/CLMQCNsF/10521599566-c7921aa65f-b.jpg"},
        {category: "object", name: "Rubiks Cube", url: "https://i.postimg.cc/6qfNmpyF/Rubiks-Cube-11913436786.jpg"},
        {category: "game", name: "Factorio", url: "https://i.postimg.cc/1R2Rn8Q5/Screen-Shot-2018-10-03-at-5-25-28-PM.png"},
        {category: "game", name: "The Witcher 3", url: "https://i.postimg.cc/bv48G57V/Games-The-Witcher-3-Wild-Hunt-They-messed-with-the-wrong-person-RGB.jpg"},
        {category: "game", name: "Stardew Valley", url: "https://i.postimg.cc/gkN0cmDG/maxresdefault.jpg"},
        {category: "person", name: "Emmanuel Macron", url: "https://i.postimg.cc/gjJGnBmn/104510929-emmanuel-macron.jpg"},
        {category: "game", name: "Starcraft 2", url: "https://i.postimg.cc/V5yynx5N/IcltHtX.png"},
        {category: "person", name: "John F. Kennedy", url: "https://i.postimg.cc/85b5001C/John-F-Kennedy.jpg"},
        {category: "event", name: "Rodeo", url: "https://i.postimg.cc/0N86YSRm/rodeo-action-at-the-cheyenne-frontier-days-celebration-in-wyomings-capital-c6127b-1024.jpg"},
        {category: "programming language", name: "Javascript", url: "https://i.postimg.cc/k4hrGQsc/javascript.png"},
        {category: "programming language", name: "Java", url: "https://i.postimg.cc/qq89LP0m/Java-Emblem.jpg"},
        {category: "operating system", name: "Linux", url: "https://i.postimg.cc/TPMn8BXj/linux-tux-hero-2.jpg"},
        {category: "animal", name: "sea turtle", url: "https://i0.wp.com/eos.org/wp-content/uploads/2021/04/loggerhead.jpg?fit=820%2C615"},
        {category: "person", name: "Freddie Mercury", url: "https://i.postimg.cc/CL4G8S9R/Freddie-Mercury-Live-Aid-Queen-Wembley-Stadium-July-13-1985.jpg"},
        {category: "dog breed", name: "Poodle", url: "https://i.postimg.cc/xjLftCf1/poodle-medium-standard1.jpg"},
        {category: "dog breed", name: "German Shepherd", url: "https://i.postimg.cc/wMgSW921/German-Shepherd-Health-Panel-600px.jpg"},
        {category: "animal", name: "Red Panda", url: "https://i.postimg.cc/QtWCJJt6/Red-Panda-Gizmo-004-Birmingham-Zoo-4-3-21-scaled.jpg"},
        {category: "animal", name: "Chimpanzee", url: "https://i.postimg.cc/T1gyfJvy/new-website-story-banners-7.jpg"},
        {category: "dog breed", name: "Chihuahua", url: "https://i.postimg.cc/9XbSm51B/chihuahua.jpg"},
        {category: "planet", name: "Venus", url: "https://i.postimg.cc/G3JSmw3p/image.jpg"},
        {category: "planet", name: "Uranus", url: "https://i.postimg.cc/dthdSrfK/0x0.jpg"},
        {category: "planet", name: "Neptune", url: "https://i.postimg.cc/BnW8YyDx/neptune-stars-ian-mckinnell.jpg"},
        {category: "planet", name: "Mercury", url: "https://i.postimg.cc/hPswpFNY/01-mercury-pia15190-orig.webp"},
        {category: "person", name: "Edward Snowden", url: "https://i.postimg.cc/N06JZ1ZM/MV5-BZj-Ew-Zm-Iy-Zj-Qt-ZDc2-MS00-Mzdi-LTk5-OTYt-MWE5-Nz-Vj-Nj-E4-MWFm-Xk-Ey-Xk-Fqc-Gde-QXVy-NDkz-NTM2-ODg-V1.jpg"},
        {category: "person", name: "Mr. Beast", url: "https://i.postimg.cc/7PjB4G72/MrBeast.png"},
    ],
    hard: [
        {category: "person", name: "Elton John", url: "https://i.postimg.cc/9X7nqNPv/Elton-John-Cannes-2019.jpg"},
        {category: "architecture", name: "Veranda", url: "https://i.postimg.cc/yYTnmqDr/1200px-Grande-Verandah.jpg"},
        {category: "TV Show", name: "Better Call Saul", url: "https://i.postimg.cc/SKGyqxRf/better-call-saul-y-como-el-final-se-revela-en-breaking-bad.jpg"},
        {category: "country", name: "Kazakhstan", url: "https://i.postimg.cc/6prKLprx/1000px-Flag-of-Kazakhstan-svg.png"},
        {category: "operating system", name: "Ubuntu", url: "https://i.postimg.cc/d11KYRzJ/1200px-Logo-ubuntu-cof-orange-hex-svg.png"},
        {category: "movie", name: "1984", url: "https://i.postimg.cc/fLZftBwh/Rosen-1984.jpg"},
        {category: "dog breed", name: "Doberman", url: "https://i.postimg.cc/Y96VXpRJ/44444.jpg"},
        {category: "app", name: "Facebook Messenger", url: "https://i.postimg.cc/GmTt2vNQ/image.jpg"},
        {category: "person", name: "Malala Yousafzai", url: "https://i.postimg.cc/3rktj599/Malala-Yousafzai-cropped.jpg"},
        {category: "programming language", name: "Ruby", url: "https://i.postimg.cc/L6PXd547/flat-750x1000-075-f-u6.jpg"},
        {category: "programming language", name: "Scala", url: "https://i.postimg.cc/NMWKTHf6/scala-490x490.webp"},
        {category: "person", name: "Lewis Hamilton", url: "https://i.postimg.cc/1z8RH3dJ/640px-Lewis-Hamilton-2016-Malaysia-2.jpg"},
        {category: "person", name: "Max Verstappen", url: "https://i.postimg.cc/8ctx9hJW/XPB-1126234-Hi-Res.jpg"},
        {category: "person", name: "Sandra Bullock", url: "https://i.postimg.cc/m21S0YHs/image.jpg"},
        {category: "game", name: "Detroit Become Human", url: "https://i.postimg.cc/hGv1g6yf/1280x720.jpg"},
        {category: "animal", name: "Axolotl", url: "https://i.postimg.cc/0yn1hMF9/baby-axolotl.jpg"},
        {category: "object", name: "The Hubble Telescope", url: "https://i.postimg.cc/0yrtnzY6/hubble-space-telescope-0420221.jpg"},
    ],
}